spring.application.name=csufconnect-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/csufconnect
spring.datasource.username=justin
spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=update

spring.mvc.cors.allowed-origins=http://localhost:5173, http://localhost:4173
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
spring.mvc.cors.max-age=3600